from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QPushButton, QLabel, QVBoxLayout, QWidget
from PyQt5.QtGui import QImage, QPixmap
import requests, pyperclip, functools

class Ui_MovieWindow(QWidget):

    def __init__(self):
        super().__init__()
        
    def setupUi(self, MovieForm):
        MovieForm.setObjectName("MovieForm")
        MovieForm.resize(881, 520)
        self.ratedLabelLabel = QtWidgets.QLabel(MovieForm)
        self.ratedLabelLabel.setGeometry(QtCore.QRect(760, 200, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.ratedLabelLabel.setFont(font)
        self.ratedLabelLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ratedLabelLabel.setObjectName("ratedLabelLabel")
        self.awardsLabel = QtWidgets.QLabel(MovieForm)
        self.awardsLabel.setGeometry(QtCore.QRect(600, 320, 271, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.awardsLabel.setFont(font)
        self.awardsLabel.setText("")
        self.awardsLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.awardsLabel.setWordWrap(True)
        self.awardsLabel.setObjectName("awardsLabel")
        self.imdbIdLabelLabel = QtWidgets.QLabel(MovieForm)
        self.imdbIdLabelLabel.setGeometry(QtCore.QRect(740, 20, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.imdbIdLabelLabel.setFont(font)
        self.imdbIdLabelLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.imdbIdLabelLabel.setObjectName("imdbIdLabelLabel")
        self.metacriticLabel = QtWidgets.QLabel(MovieForm)
        self.metacriticLabel.setGeometry(QtCore.QRect(810, 280, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.metacriticLabel.setFont(font)
        self.metacriticLabel.setText("")
        self.metacriticLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.metacriticLabel.setWordWrap(True)
        self.metacriticLabel.setObjectName("metacriticLabel")
        self.releasedLabel = QtWidgets.QLabel(MovieForm)
        self.releasedLabel.setGeometry(QtCore.QRect(580, 200, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.releasedLabel.setFont(font)
        self.releasedLabel.setText("")
        self.releasedLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.releasedLabel.setWordWrap(True)
        self.releasedLabel.setObjectName("releasedLabel")
        self.runtimeLabelLabel = QtWidgets.QLabel(MovieForm)
        self.runtimeLabelLabel.setGeometry(QtCore.QRect(310, 200, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.runtimeLabelLabel.setFont(font)
        self.runtimeLabelLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.runtimeLabelLabel.setObjectName("runtimeLabelLabel")
        self.plotLabel = QtWidgets.QLabel(MovieForm)
        self.plotLabel.setGeometry(QtCore.QRect(350, 110, 521, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.plotLabel.setFont(font)
        self.plotLabel.setText("")
        self.plotLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.plotLabel.setWordWrap(True)
        self.plotLabel.setObjectName("plotLabel")
        self.directorLabelLabel = QtWidgets.QLabel(MovieForm)
        self.directorLabelLabel.setGeometry(QtCore.QRect(310, 360, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.directorLabelLabel.setFont(font)
        self.directorLabelLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.directorLabelLabel.setObjectName("directorLabelLabel")
        self.productionLabel = QtWidgets.QLabel(MovieForm)
        self.productionLabel.setGeometry(QtCore.QRect(390, 400, 481, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.productionLabel.setFont(font)
        self.productionLabel.setText("")
        self.productionLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.productionLabel.setWordWrap(True)
        self.productionLabel.setObjectName("productionLabel")
        self.directorLabel = QtWidgets.QLabel(MovieForm)
        self.directorLabel.setGeometry(QtCore.QRect(380, 360, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.directorLabel.setFont(font)
        self.directorLabel.setText("")
        self.directorLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.directorLabel.setWordWrap(True)
        self.directorLabel.setObjectName("directorLabel")
        self.languageLabelLabel = QtWidgets.QLabel(MovieForm)
        self.languageLabelLabel.setGeometry(QtCore.QRect(600, 240, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.languageLabelLabel.setFont(font)
        self.languageLabelLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.languageLabelLabel.setObjectName("languageLabelLabel")
        self.ratedLabel = QtWidgets.QLabel(MovieForm)
        self.ratedLabel.setGeometry(QtCore.QRect(810, 200, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.ratedLabel.setFont(font)
        self.ratedLabel.setText("")
        self.ratedLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.ratedLabel.setWordWrap(True)
        self.ratedLabel.setObjectName("ratedLabel")
        self.iMDBLabel = QtWidgets.QLabel(MovieForm)
        self.iMDBLabel.setGeometry(QtCore.QRect(360, 280, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.iMDBLabel.setFont(font)
        self.iMDBLabel.setText("")
        self.iMDBLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.iMDBLabel.setWordWrap(True)
        self.iMDBLabel.setObjectName("iMDBLabel")
        self.genreLabel = QtWidgets.QLabel(MovieForm)
        self.genreLabel.setGeometry(QtCore.QRect(360, 240, 211, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.genreLabel.setFont(font)
        self.genreLabel.setText("")
        self.genreLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.genreLabel.setWordWrap(True)
        self.genreLabel.setObjectName("genreLabel")
        self.productionLabelLabel = QtWidgets.QLabel(MovieForm)
        self.productionLabelLabel.setGeometry(QtCore.QRect(310, 400, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.productionLabelLabel.setFont(font)
        self.productionLabelLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.productionLabelLabel.setObjectName("productionLabelLabel")
        self.languageLabel = QtWidgets.QLabel(MovieForm)
        self.languageLabel.setGeometry(QtCore.QRect(680, 240, 191, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.languageLabel.setFont(font)
        self.languageLabel.setText("")
        self.languageLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.languageLabel.setWordWrap(True)
        self.languageLabel.setObjectName("languageLabel")
        self.countryLabel = QtWidgets.QLabel(MovieForm)
        self.countryLabel.setGeometry(QtCore.QRect(380, 320, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.countryLabel.setFont(font)
        self.countryLabel.setText("")
        self.countryLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.countryLabel.setWordWrap(True)
        self.countryLabel.setObjectName("countryLabel")
        self.boxOfficeLabel = QtWidgets.QLabel(MovieForm)
        self.boxOfficeLabel.setGeometry(QtCore.QRect(680, 360, 191, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.boxOfficeLabel.setFont(font)
        self.boxOfficeLabel.setText("")
        self.boxOfficeLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.boxOfficeLabel.setWordWrap(True)
        self.boxOfficeLabel.setObjectName("boxOfficeLabel")
        self.countryLabelLabel = QtWidgets.QLabel(MovieForm)
        self.countryLabelLabel.setGeometry(QtCore.QRect(310, 320, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.countryLabelLabel.setFont(font)
        self.countryLabelLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.countryLabelLabel.setObjectName("countryLabelLabel")
        self.rottenTomatoesLabelLabel = QtWidgets.QLabel(MovieForm)
        self.rottenTomatoesLabelLabel.setGeometry(QtCore.QRect(480, 280, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.rottenTomatoesLabelLabel.setFont(font)
        self.rottenTomatoesLabelLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.rottenTomatoesLabelLabel.setObjectName("rottenTomatoesLabelLabel")
        self.imdbIdLabel = QtWidgets.QLabel(MovieForm)
        self.imdbIdLabel.setGeometry(QtCore.QRect(800, 20, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.imdbIdLabel.setFont(font)
        self.imdbIdLabel.setText("")
        self.imdbIdLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.imdbIdLabel.setWordWrap(True)
        self.imdbIdLabel.setObjectName("imdbIdLabel")
        self.copyDiscordButton = QtWidgets.QPushButton(MovieForm)
        self.copyDiscordButton.setGeometry(QtCore.QRect(660, 460, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.copyDiscordButton.setFont(font)
        self.copyDiscordButton.setFlat(False)
        self.copyDiscordButton.setObjectName("copyDiscordButton")
        self.posterImage = QtWidgets.QLabel(MovieForm)
        self.posterImage.setGeometry(QtCore.QRect(0, 0, 300, 444))
        self.posterImage.setMinimumSize(QtCore.QSize(300, 444))
        self.posterImage.setMaximumSize(QtCore.QSize(300, 444))
        self.posterImage.setText("")
        self.posterImage.setAlignment(QtCore.Qt.AlignCenter)
        self.posterImage.setObjectName("posterImage")
        self.actorsLabel = QtWidgets.QLabel(MovieForm)
        self.actorsLabel.setGeometry(QtCore.QRect(370, 60, 511, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.actorsLabel.setFont(font)
        self.actorsLabel.setText("")
        self.actorsLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.actorsLabel.setWordWrap(True)
        self.actorsLabel.setObjectName("actorsLabel")
        self.boxOfficeLabelLabel = QtWidgets.QLabel(MovieForm)
        self.boxOfficeLabelLabel.setGeometry(QtCore.QRect(610, 360, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.boxOfficeLabelLabel.setFont(font)
        self.boxOfficeLabelLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.boxOfficeLabelLabel.setObjectName("boxOfficeLabelLabel")
        self.metacriticLabelLabel = QtWidgets.QLabel(MovieForm)
        self.metacriticLabelLabel.setGeometry(QtCore.QRect(730, 280, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.metacriticLabelLabel.setFont(font)
        self.metacriticLabelLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.metacriticLabelLabel.setObjectName("metacriticLabelLabel")
        self.releasedLabelLabel = QtWidgets.QLabel(MovieForm)
        self.releasedLabelLabel.setGeometry(QtCore.QRect(510, 200, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.releasedLabelLabel.setFont(font)
        self.releasedLabelLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.releasedLabelLabel.setObjectName("releasedLabelLabel")
        self.iMDBLabelLabel = QtWidgets.QLabel(MovieForm)
        self.iMDBLabelLabel.setGeometry(QtCore.QRect(310, 280, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.iMDBLabelLabel.setFont(font)
        self.iMDBLabelLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.iMDBLabelLabel.setObjectName("iMDBLabelLabel")
        self.seperatorLine = QtWidgets.QFrame(MovieForm)
        self.seperatorLine.setGeometry(QtCore.QRect(0, 440, 881, 20))
        self.seperatorLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.seperatorLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.seperatorLine.setObjectName("seperatorLine")
        self.titleLabel = QtWidgets.QLabel(MovieForm)
        self.titleLabel.setGeometry(QtCore.QRect(350, 20, 371, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.titleLabel.setFont(font)
        self.titleLabel.setText("")
        self.titleLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.titleLabel.setWordWrap(True)
        self.titleLabel.setOpenExternalLinks(False)
        self.titleLabel.setObjectName("titleLabel")
        self.plotLabelLabel = QtWidgets.QLabel(MovieForm)
        self.plotLabelLabel.setGeometry(QtCore.QRect(310, 110, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.plotLabelLabel.setFont(font)
        self.plotLabelLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.plotLabelLabel.setObjectName("plotLabelLabel")
        self.runtimeLabel = QtWidgets.QLabel(MovieForm)
        self.runtimeLabel.setGeometry(QtCore.QRect(380, 200, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.runtimeLabel.setFont(font)
        self.runtimeLabel.setText("")
        self.runtimeLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.runtimeLabel.setWordWrap(True)
        self.runtimeLabel.setObjectName("runtimeLabel")
        self.titleLabelLabel = QtWidgets.QLabel(MovieForm)
        self.titleLabelLabel.setGeometry(QtCore.QRect(310, 20, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.titleLabelLabel.setFont(font)
        self.titleLabelLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.titleLabelLabel.setObjectName("titleLabelLabel")
        self.actorsLabelLabel = QtWidgets.QLabel(MovieForm)
        self.actorsLabelLabel.setGeometry(QtCore.QRect(310, 60, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.actorsLabelLabel.setFont(font)
        self.actorsLabelLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.actorsLabelLabel.setObjectName("actorsLabelLabel")
        self.awardsLabelLabel = QtWidgets.QLabel(MovieForm)
        self.awardsLabelLabel.setGeometry(QtCore.QRect(540, 320, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.awardsLabelLabel.setFont(font)
        self.awardsLabelLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.awardsLabelLabel.setObjectName("awardsLabelLabel")
        self.rottenTomatoesLabel = QtWidgets.QLabel(MovieForm)
        self.rottenTomatoesLabel.setGeometry(QtCore.QRect(610, 280, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.rottenTomatoesLabel.setFont(font)
        self.rottenTomatoesLabel.setText("")
        self.rottenTomatoesLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.rottenTomatoesLabel.setWordWrap(True)
        self.rottenTomatoesLabel.setObjectName("rottenTomatoesLabel")
        self.genreLabelLabel = QtWidgets.QLabel(MovieForm)
        self.genreLabelLabel.setGeometry(QtCore.QRect(310, 240, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.genreLabelLabel.setFont(font)
        self.genreLabelLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.genreLabelLabel.setObjectName("genreLabelLabel")
        self.saveMovieButton = QtWidgets.QPushButton(MovieForm)
        self.saveMovieButton.setGeometry(QtCore.QRect(440, 460, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.saveMovieButton.setFont(font)
        self.saveMovieButton.setFlat(False)
        self.saveMovieButton.setObjectName("saveMovieButton")

        self.retranslateUi(MovieForm)
        QtCore.QMetaObject.connectSlotsByName(MovieForm)
        
        self.copyDiscordButton.clicked.connect(self.copy_discord_version_to_clipboard)
        self.saveMovieButton.clicked.connect(self.save_movie_to_list)


    def retranslateUi(self, MovieForm):
        _translate = QtCore.QCoreApplication.translate
        MovieForm.setWindowTitle(_translate("MovieForm", "Movie Details"))
        self.ratedLabelLabel.setText(_translate("MovieForm", "Rated:"))
        self.imdbIdLabelLabel.setText(_translate("MovieForm", "imdbID:"))
        self.runtimeLabelLabel.setText(_translate("MovieForm", "Runtime:"))
        self.directorLabelLabel.setText(_translate("MovieForm", "Director:"))
        self.languageLabelLabel.setText(_translate("MovieForm", "Language:"))
        self.productionLabelLabel.setText(_translate("MovieForm", "Production:"))
        self.countryLabelLabel.setText(_translate("MovieForm", "Country:"))
        self.rottenTomatoesLabelLabel.setText(_translate("MovieForm", "Rotten Tomatoes:"))
        self.copyDiscordButton.setText(_translate("MovieForm", "Copy Discord Version To Clipboard"))
        self.boxOfficeLabelLabel.setText(_translate("MovieForm", "BoxOffice:"))
        self.metacriticLabelLabel.setText(_translate("MovieForm", "Metacritic:"))
        self.releasedLabelLabel.setText(_translate("MovieForm", "Released:"))
        self.iMDBLabelLabel.setText(_translate("MovieForm", "IMDB:"))
        self.plotLabelLabel.setText(_translate("MovieForm", "Plot:"))
        self.titleLabelLabel.setText(_translate("MovieForm", "Title:"))
        self.actorsLabelLabel.setText(_translate("MovieForm", "Actors:"))
        self.awardsLabelLabel.setText(_translate("MovieForm", "Awards:"))
        self.genreLabelLabel.setText(_translate("MovieForm", "Genre:"))
        self.saveMovieButton.setText(_translate("MovieForm", "Save Movie To List"))
                
    def setUiMainWindow(self, ui_main_window):
        self.ui_main_window = ui_main_window
        
    def setMovie(self, movie):
        self.movie = movie

    def populateMovieDetails(self):        
        image = QImage()
        image.loadFromData(requests.get(self.movie['Poster']).content)

        self.posterImage.setPixmap(QPixmap(image))
        self.titleLabel.setText(self.movie['Title'])
        self.imdbIdLabel.setText(self.movie['imdbID'])
        self.actorsLabel.setText(self.movie['Actors'])
        self.plotLabel.setText(self.movie['Plot'])
        self.runtimeLabel.setText(self.movie['Runtime'])
        self.releasedLabel.setText(self.movie['Released'])
        self.ratedLabel.setText(self.movie['Rated'])   
        self.genreLabel.setText(self.movie['Genre'])
        self.languageLabel.setText(self.movie['Language'])
        self.iMDBLabel.setText(self.movie['Ratings'][0]['Value']) if(len(self.movie['Ratings']) >= 1) else self.iMDBLabel.setText('N/A')
        self.rottenTomatoesLabel.setText(self.movie['Ratings'][1]['Value']) if(len(self.movie['Ratings']) >= 2) else self.rottenTomatoesLabel.setText('N/A')
        self.metacriticLabel.setText(self.movie['Ratings'][2]['Value']) if(len(self.movie['Ratings']) >= 3) else self.metacriticLabel.setText('N/A')        
        self.countryLabel.setText(self.movie['Country'])
        self.awardsLabel.setText(self.movie['Awards'])
        self.directorLabel.setText(self.movie['Director'])
        self.boxOfficeLabel.setText(self.movie['BoxOffice'])
        self.productionLabel.setText(self.movie['Production'])
        
        # self.CopyDiscordButton.clicked.connect(functools.partial(self.copy_discord_version_to_clipboard, movie=self.movie))

    def save_movie_to_list(self):
        discord_movie = self.get_discord_version_of_movie(self.movie)
        self.ui_main_window.add_movie_to_list(discord_movie)
    

    def copy_discord_version_to_clipboard(self):
        discord_movie = self.get_discord_version_of_movie(self.movie)
        pyperclip.copy(discord_movie)
        
        
    def get_discord_version_of_movie(self, movie):
        return 'https://www.imdb.com/title/{ImdbId}\n' \
                'https://www.imdb.com/title/{ImdbId}/parentalguide\n' \
                '```css\n' \
                '[ {Title} | ⌚ {Runtime} | ⭐ {ImdbRating} | 📅 {Released} | {Rated} ]\n' \
                '\'{Plot}\'\n' \
                '```'.format(ImdbId=movie['imdbID'],
                             Title=movie['Title'], 
                             Runtime=movie['Runtime'], 
                             ImdbRating=movie['Ratings'][0]['Value'],
                             Released=movie['Released'],
                             Rated=movie['Rated'],
                             Plot=movie['Plot'])